/**
 * Kriya Pain Diagnostics — Core Types
 * Ported from App.jsx. Client-side only.
 */

export type Flag = 'red' | 'yellow' | 'green';
export type RegionKey = 'back' | 'neck' | 'shoulder' | 'knee';

export interface Condition {
  name: string;
  flag: Flag;
  age: string;
  gender: 'both' | 'M>F' | 'F>M' | 'male' | 'female';
  feel: string;
  agg: string[];
  rel: string[];
  dur: string;
  status: string;
  feat: string[];
  neuro: 'affected' | 'wnl' | 'maybe';
}

export type ConditionsDB = Record<RegionKey, Condition[]>;

/**
 * Patient data collected across the questionnaire.
 * Keys are QC codes (L010301 etc.) plus derived fields.
 * Every field is optional — the flow validates required fields per step.
 */
export interface PatientData {
  // Demographics
  L010401?: 'Male' | 'Female' | 'Transgender' | 'Prefer not to say'; // gender
  L010301?: string;        // age (numeric string)
  height?: string;         // cm
  weight?: string;         // kg
  bmi?: number;            // derived
  // Lifestyle
  L010701?: string;        // occupation
  L030101?: string;        // exercise frequency
  // Pain region
  L030201?: string;        // primary region
  L030201b?: string;       // secondary region
  // Pain details
  L030401?: string;        // pain description
  L030501?: number;        // pain scale 1-10 (default 5)
  L030601?: string;        // feeling (constant/intermittent)
  L030701?: string;        // activity-pain relationship
  // Symptoms & status
  L030801?: string[];      // accompanying symptoms (multi)
  L030901?: string;        // trend (worsening/improving/same)
  // Medical history
  L031001?: string[];      // conditions (multi)
  // Duration, relapse, diagnoses, deficiencies, surgeries
  L150101?: string;        // pain duration
  L150102?: 'Yes' | 'No';  // relapse
  L170101?: string[];      // diagnoses (multi)
  L170201?: string[];      // deficiencies (multi)
  L170301?: string;        // past surgery
  L170302?: 'Yes' | 'No';  // recent surgery
  // Origination & aggravation
  L190101?: string;        // first incidence
  L190201?: string;        // aggravating activity
  L190202?: string;        // aggravation duration
  // Relief
  L210101?: string;        // relief activity
  L210102?: string;        // relief duration
  // Past treatment
  L230101?: string;        // past treatment
  L230102?: string;        // treatment outcome
  // Follow-ups (dynamic keys FU_<condition>)
  [key: `FU_${string}`]: string | undefined;
}

export interface ScoredCondition {
  name: string;
  score: number;
  flag: Flag;
}

export type SeverityBucket = 'Mild' | 'Moderate' | 'Severe' | 'Emergency';

export interface SeverityResult {
  total: number;
  bucket: SeverityBucket;
}

export type Confidence = 'High' | 'Moderate' | 'Low';

export interface DiagnosticResult {
  user: { age?: string; gender?: string; bmi?: number };
  pain: {
    region?: string;
    duration?: string;
    scale?: number;
    description?: string;
    feeling?: string;
  };
  severity: SeverityResult;
  scores: Record<string, number>;
  top_3: ScoredCondition[];
  confidence: Confidence;
  action: string;
  disclaimer: string;
  noPain?: undefined;
}

export interface NoPainResult {
  noPain: true;
  action: string;
}

export type EngineOutput = DiagnosticResult | NoPainResult;

export interface BmiInsight {
  t: string; // title
  m: string; // message
  c: string; // colour
  e: string; // emoji
}

export interface ActivityInsight {
  t: string;     // title
  items: string[];
  c: string;     // colour
}

/**
 * Chat transcript entry.
 * Bot messages are generated by the questionnaire; user messages are
 * echoed back when a selection/answer is made.
 */
export type ChatEntry =
  | { id: string; role: 'bot'; kind: 'text'; text: string }
  | { id: string; role: 'bot'; kind: 'insight'; emoji: string; text: string; color: string }
  | { id: string; role: 'bot'; kind: 'bmi'; insight: BmiInsight; bmi: number }
  | { id: string; role: 'bot'; kind: 'mini-diagnosis'; insight: ActivityInsight }
  | { id: string; role: 'bot'; kind: 'severity'; severity: SeverityResult }
  | { id: string; role: 'bot'; kind: 'red-flag'; text: string }
  | { id: string; role: 'bot'; kind: 'result'; result: EngineOutput }
  | { id: string; role: 'bot'; kind: 'thinking'; text: string }
  | {
      id: string;
      role: 'bot';
      kind: 'chips-question';
      /** Prompt shown above the option buttons. */
      prompt?: string;
      /** Selectable options rendered inside the bubble. */
      options: string[];
      /** When true, user must pick one or more and commit via a Send button. */
      multi: boolean;
      /** Once the user answers, holds the chosen value(s); buttons become disabled. */
      resolved?: string | string[];
    }
  | {
      id: string;
      role: 'bot';
      kind: 'extraction-summary';
      /** Human-readable labels for each extracted field, in display order. */
      labels: { key: string; label: string }[];
      /** Raw patches to apply on confirm. */
      patches: Partial<PatientData> & { height?: string; weight?: string };
      /** Optional explanatory note from the extractor. */
      notes?: string;
      /** Resolved once the user clicks Confirm or Edit. */
      resolved?: 'confirmed' | 'edited';
    }
  | { id: string; role: 'user'; kind: 'text'; text: string };
